name: tourism_connect_benin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  hugeicons: ^1.1.7
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.2
  
  # State Management
  provider: ^6.1.5+1
  flutter_riverpod: ^3.3.2
  
  # Navigation
  go_router: ^17.2.3
  
  # Storage
  shared_preferences: ^2.5.5
  
  # Backend (Supabase)
  
  # Remplacer la version actuelle
  supabase_flutter: ^2.15.2  # Utilise la version la plus récente
  
  # Network & Images
  dio: ^5.9.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.2
  
  # Maps
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  
  # Permissions & Links
  permission_handler: ^12.0.3
  url_launcher: ^6.3.2
  
  # Utils
  intl: ^0.20.2
  smooth_page_indicator: ^2.0.1
  shimmer: ^3.0.0
  
  # PDF
  pdf: ^3.12.0
  printing: ^5.14.3
# À la fin du fichier, après dependencies
dependency_overrides:
  sign_in_with_apple: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/yoma.png
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/yome.png"